### PR TITLE
Fix issues with summarise() calls containing complex expressions

### LINKED ISSUE #153: Error when using summarise() with literal values
``` r
library(dplyr, warn.conflicts = FALSE)
library(substrait, warn.conflicts = FALSE)

mtcars %>% 
  summarise(1L) %>%
  collect() 
#>   1L
#> 1  1

mtcars %>% 
  duckdb_substrait_compiler() %>%
  summarise(1L) %>%
  collect() 
#> Error in as_substrait.default(result, "substrait.AggregateFunction"): Can't create substrait.AggregateFunction from object of type 'integer'
```

### LINKED ISSUE #155: Complex expressions in summarise() body not supported
``` r
library(dplyr, warn.conflicts = FALSE)
library(substrait, warn.conflicts = FALSE)

mtcars %>% 
  group_by(am, gear) %>%
  summarise((am+1)) %>%
  collect() 
#> `summarise()` has grouped output by 'am', 'gear'. You can override using the
#> `.groups` argument.
#> # A tibble: 32 × 3
#> # Groups:   am, gear [4]
#>       am  gear `(am + 1)`
#>    <dbl> <dbl>      <dbl>
#>  1     0     3          1
#>  2     0     3          1
#>  3     0     3          1
#>  4     0     3          1
#>  5     0     3          1
#>  6     0     3          1
#>  7     0     3          1
#>  8     0     3          1
#>  9     0     3          1
#> 10     0     3          1
#> # … with 22 more rows

mtcars %>% 
  duckdb_substrait_compiler() %>%
  group_by(am, gear) %>%
  summarise((am+1)) %>%
  collect() 
#> Error: callr subprocess failed: rapi_prepare: Failed to prepare query CALL from_substrait('\x0a\x02\x08\x01\x12\x09\x1a\x07\x08\x01\x10\x02\x1a\x01\x2b\x12\x09\x1a\x07\x08\x01\x10\x03\x1a\x01\x28\x1a\xd7\x01\x12\xd4\x01\x0a\xbd\x01\x22\xba\x01\x12\x7b\x0a\x79\x12\x66\x0a\x03\x6d\x70\x67\x0a\x03\x63\x79\x6c\x0a\x04\x64\x69\x73\x70\x0a\x02\x68\x70\x0a\x04\x64\x72\x61\x74\x0a\x02\x77\x74\x0a\x04\x71\x73\x65\x63\x0a\x02\x76\x73\x0a\x02\x61\x6d\x0a\x04\x67\x65\x61\x72\x0a\x04\x63\x61\x72\x62\x12\x2c\x0a\x02\x5a\x00\x0a\x02\x5a\x00\x0a\x02\x5a\x00\x0a\x02\x5a\x00\x0a\x02\x5a\x00\x0a\x02\x5a\x00\x0a\x02\x5a\x00\x0a\x02\x5a\x00\x0a\x02\x5a\x00\x0a\x02\x5a\x00\x0a\x02\x5a\x00\x3a\x0f\x0a\x0d\x6e\x61\x6d\x65\x64\x5f\x74\x61\x62\x6c\x65\x5f\x31\x1a\x14\x0a\x08\x12\x06\x0a\x04\x12\x02\x08\x08\x0a\x08\x12\x06\x0a\x04\x12\x02\x08\x09\x22\x25\x0a\x23\x08\x03\x12\x1d\x1a\x1b\x08\x02\x12\x08\x12\x06\x0a\x04\x12\x02\x08\x08\x12\x0b\x0a\x09\x59\x00\x00\x00\x00\x00\x00\xf0\x3f\x1a\x00\x2a\x00\x12\x02\x61\x6d\x12\x04\x67\x65\x61\x72\x12\x08\x28\x61\x6d\x20\x2b\x20\x31\x29'::BLOB)
#> Error: Catalog Error: Scalar Function with name ( does not exist!
#> Did you mean "|"?
```

<sup>Created on 2022-06-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by thisisnic**
Before:
``` r
library(dplyr)
library(substrait)

tibble::tibble(x = 1:3) %>%
  duckdb_substrait_compiler() %>%
  summarise(y = sum(x + 1, na.rm = TRUE)) %>%
  collect()
#> # A tibble: 1 × 1
#>       y
#>   <dbl>
#> 1     9

tibble::tibble(x = 1:3) %>%
  duckdb_substrait_compiler() %>%
  summarise(y = sum(x, na.rm = TRUE) + 1) %>%
  collect()
#> Error in as_substrait.substrait_proto_message(X[[i]], ...): identical(x_qualified_name, .qualified_name) is not TRUE
```

After:
``` r
library(dplyr)
library(substrait)

tibble::tibble(x = 1:3) %>%
  duckdb_substrait_compiler() %>%
  summarise(y = sum(x + 1, na.rm = TRUE)) %>%
  collect()
#> # A tibble: 1 × 1
#>       y
#>   <dbl>
#> 1     9

tibble::tibble(x = 1:3) %>%
  duckdb_substrait_compiler() %>%
  summarise(y = sum(x, na.rm = TRUE) + 1) %>%
  collect()
#> # A tibble: 1 × 1
#>       y
#>   <dbl>
#> 1     7
```

Fixes #155 
Fixes #153

### CODE REVIEW

File: DESCRIPTION [hunk 1]
```diff
@@ -37,7 +37,8 @@ Imports:
     RProtoBuf,
     vctrs,
     dplyr,
-    R6
+    R6,
+    purrr
```
Comment (paleolimbot) [inline DESCRIPTION:41]: I'd like to avoid a purrr dependency if we can (most tidyverse packages themselves avoid a purr dependency too). Most of this package uses lapply and vapply at the moment.

File: R/aggregate-rel.R [hunk 2]
```diff
@@ -99,3 +178,52 @@ substrait_group_by <- function(.compiler, ...) {
...
+
+#' @export
+as_substrait.substrait_AggregateFunction <- function(x, .ptype = NULL, ...) {
+  if (is.null(.ptype)) {
+    .ptype <- x
+  }
+
+  switch(make_qualified_name(.ptype),
+    "substrait.Expression" = {
+      current_compiler()$post_mutate(x)
```
Comment (paleolimbot) [inline R/aggregate-rel.R:190]: Did this PR add a `post_mutate()` method to the compiler?

Comment (thisisnic) [reply R/aggregate-rel.R:190]: No, this was from a comment you made on the issue, but removing it as it's implemented elsewhere.

File: R/aggregate-rel.R [hunk 3]
```diff
@@ -65,8 +134,18 @@ substrait_aggregate <- function(.compiler, ...) {
...
+  grps <- .compiler$groups
   .compiler$groups <- NULL
 
+  if (length(ctx$post_mutate)) {
+    # add in post-mutate cols
+    vars_to_select <- c(names(grps), names(quos))
+
+    .compiler <- substrait_project(.compiler, !!!syms(.compiler$schema$names), !!!ctx$post_mutate)
+
+    .compiler <- substrait_select(.compiler, !!!syms(vars_to_select))
```
[the remark this answers is not in the document]
Comment (thisisnic) [reply R/aggregate-rel.R]: Just using project now

**Comment by thisisnic** [comment]
@paleolimbot I think I've addressed everything in your comments and this is ready for another round of reviews.

File: R/aggregate-rel.R (hunk 3 above)
[the remark this answers is not in the document]
Comment (thisisnic) [reply R/aggregate-rel.R]: Actually, I've reverted this as it breaks the tests.  We need `project()` first to create the new temporary column (it functions as a `mutate()`), followed by `select()` to literally only select the columns we want to keep.  I don't see that it is odd to do both - this follows the arrow package implementation.

File: tests/testthat/test-dplyr-summarise.R [hunk 4]
```diff
@@ -999,3 +1000,18 @@ test_that("summarise() can handle scalars and literal values", {
...
+    .input %>% summarise(y = sum(int, na.rm = TRUE) + 1) %>% collect(),
+    example_data
+  )
+
+  # Revisit this in Arrow after https://github.com/apache/arrow/issues/34501 is resolved
+  compare_dplyr_binding(
+    engine = "duckdb",
+    .input %>% summarise(y = sum(int + 1, na.rm = TRUE)) %>% collect(),
+    example_data
+  )
```
[the remark this answers is not in the document]
Comment (paleolimbot) [reply tests/testthat/test-dplyr-summarise.R:1087]: There's a line in this PR where it says `# We could have a quosure here if we have an expression like sum({{ var }})`...maybe error here instead of handle that case? This might happen if:

```r
summarise_me <- function(data, var) {
  summarise(data, sum({{ var }}))
}
```

occurs (according to the comment, which may be outdated).

File: R/aggregate-rel.R [hunk 5]
```diff
@@ -17,15 +17,90 @@ substrait_aggregate <- function(.compiler, ...) {
...
 
-  # have to rethink this because we need to keep track of a
-  # post_mutate step for expressions like sum(x) + 1
+  # inner == sum(x) + 1 [i.e. one of the inner functions is an aggregate func]
+  #   here, we have to first do the aggregation and then the projection
+  # outer == sum(x+1) [i.e. the outermost function is an aggregate func]
+  #   here, we have to first calculate the projection x+1, and then the sum
+  # both == sum(x + sum(x + 1)) [i.e. an aggregate exists at both inner and outer levels]
+  #   here, we want to do the projection x+1, then aggregate it, then project x + it, then sum that
+  # note! this is not supported!
```
Comment (paleolimbot) [inline R/aggregate-rel.R:26]: Still true?

File: R/aggregate-rel.R [hunk 6]
```diff
@@ -17,15 +17,90 @@ substrait_aggregate <- function(.compiler, ...) {
...
+
+  ctx <- rlang::env(
+    mask = .compiler,
+    aggregations = list(),
+    post_mutate = list()
+  )
+  # get the inner and outer aggregations
+  for (i in seq_along(quos)) {
+    # Iterate over the indices and not the names because names may be repeated
```
Comment (paleolimbot) [inline R/aggregate-rel.R:35]: This feels to me like it should be its own function (maybe `separate_agg_from_post_mutate()`?)

File: R/aggregate-rel.R [hunk 7]
```diff
@@ -65,8 +139,18 @@ substrait_aggregate <- function(.compiler, ...) {
   names(.compiler$.data) <- names(types)
 
   # drop groups
+  grps <- .compiler$groups
   .compiler$groups <- NULL
 
+  if (length(ctx$post_mutate) > 0) {
+    # add in post-mutate cols
+    vars_to_select <- c(names(grps), names(quos))
```
Comment (paleolimbot) [inline R/aggregate-rel.R:147]: If there are repeated names in `quos` what happens? (There is a comment above that seems to indicate that this behaviour is supported)

File: R/aggregate-rel.R [hunk 8]
```diff
@@ -65,8 +139,18 @@ substrait_aggregate <- function(.compiler, ...) {
...
+
+    .compiler <- substrait_project(.compiler, !!!rlang::syms(.compiler$schema$names), !!!ctx$post_mutate)
+
+    .compiler <- substrait_select(.compiler, !!!rlang::syms(vars_to_select))
```
Comment (paleolimbot) [inline R/aggregate-rel.R:151]: I really think you want just one `substrait_select()` here. I am pretty sure that `substrait_select()` evaluates its arguments in order so that you can do `substrait_select(!!!ctx$post_mutate, !!!rlang::syms(vars_to_select))`.

(If that doesn't work this is fine...but if you can find a way to have *one* project node here and not *two* I think it will result in a more readable/efficient plan)

**Review by paleolimbot — COMMENTED** [review]
Just a few touches! It looks great!

File: R/aggregate-rel.R (hunk 7 above)
Comment (thisisnic) [reply R/aggregate-rel.R:146]: Works as expected:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(substrait)
#> 
#> Attaching package: 'substrait'
#> The following object is masked from 'package:stats':
#> 
#>     filter

mtcars %>%
  summarise(x = sum(hp) + 1, x = sum(wt) + 1)
#>         x
#> 1 103.952

out <- mtcars %>%
  duckdb_substrait_compiler() %>%
  summarise(x = sum(hp) + 1, x = sum(wt) + 1)
#> Warning: `as_quosure()` requires an explicit environment as of rlang 0.3.0.
#> Please supply `env`.
#> This warning is displayed once per session.
#> Warning in check_na_rm_duckdb(na.rm): Missing value removal from aggregate
#> functions not supported in DuckDB, switching to na.rm = TRUE

#> Warning in check_na_rm_duckdb(na.rm): Missing value removal from aggregate
#> functions not supported in DuckDB, switching to na.rm = TRUE

collect(out)
#> # A tibble: 1 × 1
#>       x
#>   <dbl>
#> 1  104.

out$plan()
#> message of type 'substrait.Plan' with 3 fields set
#> extension_uris {
#>   extension_uri_anchor: 1
#> }
#> extensions {
#>   extension_function {
#>     extension_uri_reference: 1
#>     function_anchor: 2
#>     name: "sum"
#>   }
#> }
#> extensions {
#>   extension_function {
#>     extension_uri_reference: 1
#>     function_anchor: 3
#>     name: "+"
#>   }
#> }
#> relations {
#>   root {
#>     input {
#>       project {
#>         common {
#>           emit {
#>             output_mapping: 2
#>           }
#>         }
#>         input {
#>           aggregate {
#>             input {
#>               read {
#>                 base_schema {
#>                   names: "mpg"
#>                   names: "cyl"
#>                   names: "disp"
#>                   names: "hp"
#>                   names: "drat"
#>                   names: "wt"
#>                   names: "qsec"
#>                   names: "vs"
#>                   names: "am"
#>                   names: "gear"
#>                   names: "carb"
#>                   struct {
#>                     types {
#>                       fp64 {
#>                         nullability: NULLABILITY_NULLABLE
#>                       }
#>                     }
#>                     types {
#>                       fp64 {
#>                         nullability: NULLABILITY_NULLABLE
#>                       }
#>                     }
#>                     types {
#>                       fp64 {
#>                         nullability: NULLABILITY_NULLABLE
#>                       }
#>                     }
#>                     types {
#>                       fp64 {
#>                         nullability: NULLABILITY_NULLABLE
#>                       }
#>                     }
#>                     types {
#>                       fp64 {
#>                         nullability: NULLABILITY_NULLABLE
#>                       }
#>                     }
#>                     types {
#>                       fp64 {
#>                         nullability: NULLABILITY_NULLABLE
#>                       }
#>                     }
#>                     types {
#>                       fp64 {
#>                         nullability: NULLABILITY_NULLABLE
#>                       }
#>                     }
#>                     types {
#>                       fp64 {
#>                         nullability: NULLABILITY_NULLABLE
#>                       }
#>                     }
#>                     types {
#>                       fp64 {
#>                         nullability: NULLABILITY_NULLABLE
#>                       }
#>                     }
#>                     types {
#>                       fp64 {
#>                         nullability: NULLABILITY_NULLABLE
#>                       }
#>                     }
#>                     types {
#>                       fp64 {
#>                         nullability: NULLABILITY_NULLABLE
#>                       }
#>                     }
#>                   }
#>                 }
#>                 named_table {
#>                   names: "named_table_1"
#>                 }
#>               }
#>             }
#>             groupings {
#>             }
#>             measures {
#>               measure {
#>                 function_reference: 2
#>                 output_type {
#>                   fp64 {
#>                     nullability: NULLABILITY_NULLABLE
#>                   }
#>                 }
#>                 arguments {
#>                   value {
#>                     selection {
#>                       direct_reference {
#>                         struct_field {
#>                           field: 3
#>                         }
#>                       }
#>                       root_reference {
#>                       }
#>                     }
#>                   }
#>                 }
#>               }
#>             }
#>             measures {
#>               measure {
#>                 function_reference: 2
#>                 output_type {
#>                   fp64 {
#>                     nullability: NULLABILITY_NULLABLE
#>                   }
#>                 }
#>                 arguments {
#>                   value {
#>                     selection {
#>                       direct_reference {
#>                         struct_field {
#>                           field: 5
#>                         }
#>                       }
#>                       root_reference {
#>                       }
#>                     }
#>                   }
#>                 }
#>               }
#>             }
#>           }
#>         }
#>         expressions {
#>           scalar_function {
#>             function_reference: 3
#>             output_type {
#>               fp64 {
#>                 nullability: NULLABILITY_NULLABLE
#>               }
#>             }
#>             arguments {
#>               value {
#>                 selection {
#>                   direct_reference {
#>                     struct_field {
#>                       field: 1
#>                     }
#>                   }
#>                   root_reference {
#>                   }
#>                 }
#>               }
#>             }
#>             arguments {
#>               value {
#>                 literal {
#>                   fp64: 1
#>                 }
#>               }
#>             }
#>           }
#>         }
#>       }
#>     }
#>     names: "x"
#>   }
#> }
```

File: R/aggregate-rel.R (hunk 3 above)
[the remark this answers is not in the document]
Comment (thisisnic) [reply R/aggregate-rel.R]: Never mind, was getting mixed up here, changed now

File: tests/testthat/test-dplyr-summarise.R (hunk 4 above)
[the remark this answers is not in the document]
Comment (thisisnic) [reply tests/testthat/test-dplyr-summarise.R:1087]: We can handle this! Have added a test

File: R/aggregate-rel.R (hunk 6 above)
Comment (thisisnic) [reply R/aggregate-rel.R]: Done

File: R/aggregate-rel.R [hunk 9]
```diff
@@ -99,3 +179,38 @@ substrait_group_by <- function(.compiler, ...) {
 substrait_ungroup <- function(.compiler) {
   substrait_group_by(.compiler)
 }
+
+# This function recurses through expr, pulls out any aggregation expressions,
+# and inserts a variable name (field ref) in place of the aggregation
+extract_aggregations <- function(expr, ctx, agg_funcs) {
```
Comment (paleolimbot) [inline R/aggregate-rel.R:122]: This is the bit that floated in recently: this is designed to catch cases like `sum(x + 1)` that Arrow can't handle but Substrait can (I think). In theory this function should not need to exist!

File: R/aggregate-rel.R [hunk 10]
```diff
@@ -17,15 +17,89 @@ substrait_aggregate <- function(.compiler, ...) {
...
+      # converted to one.
+      value <- as_substrait_expression(quosure, compiler = .compiler)
+
+      # Scalars need to be added to post_mutate because they don't need
+      # to be sent to the query engine as an aggregation
+      ctx$post_mutate[[name]] <- value
+    }
+
+    # Start inspecting the expr to see what aggregations it involves
+    # TODO: generate, don't hard-code these
```
Comment (paleolimbot) [inline R/aggregate-rel.R]: This TODO should get handled in this PR. You could add a method to the SubstraitCompiler `.list_agg_functions()`?

File: R/aggregate-rel.R [hunk 11]
```diff
@@ -17,15 +17,89 @@ substrait_aggregate <- function(.compiler, ...) {
...
+    if (outer_agg) {
+      # This is something like agg(fun(x, y)
+      # It just works by normal arrow_eval, unless there's a mix of aggs and
+      # columns in the original data like agg(fun(x, agg(x)))
+      # (but that will have been caught in extract_aggregations())
+      ctx$aggregations[[name]] <- rlang::as_quosure(expr, env = ctx$quo_env)
+    } else if (all(inner_agg_exprs | !inner_is_fieldref)) {
+      # Something like: fun(agg(x), agg(y))
+      ctx$post_mutate[[name]] <- rlang::as_quosure(expr, env = ctx$quo_env)
+    }
```
Comment (paleolimbot) [inline R/aggregate-rel.R]: Is there a test for this case? I wonder if some part of `extract_aggregations()` has to exist to make this work.

File: R/aggregate-rel.R (hunk 10 above)
Comment (thisisnic) [reply R/aggregate-rel.R]: Isn't that just hard-coding it somewhere else?

Comment (paleolimbot) [reply R/aggregate-rel.R]: The default method would hard-code an empty list; the DuckDB and Arrow compilers can override that method (then at least the hard-coding is in the same file where the functions themselves are defined).

File: tests/testthat/test-aggregate-rel.R [hunk 12]
```diff
@@ -16,6 +16,7 @@ test_that("substrait_group_by() / substrait_ungroup() (un) set the grouping", {
 test_that("substrait_aggregate() can evaluate a simple aggregation expression", {
   compiler <- substrait_compiler(data.frame(a = c(1, 1, 2, 2, 3), b = 1:5))
   compiler$.fns$sum <- function(x) substrait_call_agg("sum", x)
+  compiler$.list_agg_functions <- function() list("sum")
```
Comment (thisisnic) [inline tests/testthat/test-aggregate-rel.R:19]: @paleolimbot Your test here no longer works:
```
Error in compiler$.list_agg_functions <- function() list("sum") : 
  cannot change value of locked binding for '.list_agg_functions'
```

File: R/aggregate-rel.R (hunk 10 above)
Comment (thisisnic) [reply R/aggregate-rel.R]: OK, done.

File: R/aggregate-rel.R (hunk 9 above)
Comment (paleolimbot) [reply R/aggregate-rel.R:122]: In theory we don't need any of this PR to do the TCP-H work (we could just rewrite the queries to not do `sum(x) + 1` or whatever they're doing). I don't think either of us have plans to circle back to this soon, so do I do think it's important to do while we're both thinking about it. (Also our plans will look silly if we don't address it)

File: R/aggregate-rel.R (hunk 11 above)
Comment (thisisnic) [reply R/aggregate-rel.R]: I don't understand what the comment even means tbh; any ideas?

File: R/aggregate-rel.R (hunk 9 above)
Comment (thisisnic) [reply R/aggregate-rel.R:122]: > our plans will look silly
How so?

File: R/aggregate-rel.R (hunk 11 above)
Comment (paleolimbot) [reply R/aggregate-rel.R]: I think it means that `summarise(sum(x) + sum(y))` should work (i.e., more than one aggregation could exist in each expression).

File: R/aggregate-rel.R [hunk 13]
```diff
@@ -17,15 +17,26 @@ substrait_aggregate <- function(.compiler, ...) {
...
 
-  # have to rethink this because we need to keep track of a
-  # post_mutate step for expressions like sum(x) + 1
+  # inner == sum(x) + 1 [i.e. one of the inner functions is an aggregate func]
+  #   here, we have to first do the aggregation and then the projection
+  # outer == sum(x+1) [i.e. the outermost function is an aggregate func]
+  #   here, we have to first calculate the projection x+1, and then the sum
+  # both == sum(x + sum(x + 1)) [i.e. an aggregate exists at both inner and outer levels]
+  #   here, we want to do the projection x+1, then aggregate it, then project x + it, then sum that
+  # note! this is not supported!
```
Comment (paleolimbot) [inline R/aggregate-rel.R:26]:
```suggestion
  # There are several cases to consider here:
  # outer == sum(<any expression that is not an aggregation>) [i.e. only the outermost 
  #   function is an aggregate func]. This requires no extra projections.
  # inner == sum(x) + 1 [i.e. one of the inner functions is an aggregate func but 
  #   not the outer one]. Here, we have to first do the aggregation and then
  #   the projection
  # both == sum(x + sum(x + 1)) [i.e. an aggregate exists at both inner and outer levels]
  #   This is not currently supported.
```

Comment (paleolimbot) [reply R/aggregate-rel.R:26]: This solves the issue I was referring to below...you had already modified the code to do the right thing, but this comment was left behind suggesting that our implementation did something that it no longer needed to do.

File: R/aggregate-rel.R (hunk 9 above)
Comment (paleolimbot) [reply R/aggregate-rel.R:122]: (See above...the problem here was a misleading comment, not your code!)

File: R/aggregate-rel.R [hunk 14]
```diff
@@ -99,3 +116,105 @@ substrait_group_by <- function(.compiler, ...) {
...
+    # we have to look for them by their new var names in ctx$aggregations.
+    inner_agg_exprs <- all_vars(expr) %in% names(ctx$aggregations)
+    inner_is_fieldref <- all_vars(expr) %in% names(ctx$mask$.data)
+
+    if (outer_agg) {
+      # This is something like agg(fun(x, y)
+      # It just works by normal arrow_eval, unless there's a mix of aggs and
+      # columns in the original data like agg(fun(x, agg(x)))
+      # (but that will have been caught in extract_aggregations())
+      ctx$aggregations[[name]] <- rlang::as_quosure(expr, env = ctx$quo_env)
```
Comment (paleolimbot) [inline R/aggregate-rel.R:212]:
```suggestion
      ctx$aggregations[[name]] <- rlang::as_quosure(expr, env = quo_env)
```

File: R/aggregate-rel.R [hunk 15]
```diff
@@ -99,3 +116,105 @@ substrait_group_by <- function(.compiler, ...) {
...
+    } else if (all(inner_agg_exprs | !inner_is_fieldref)) {
+      # Something like: fun(agg(x), agg(y))
+      ctx$post_mutate[[name]] <- rlang::as_quosure(expr, env = ctx$quo_env)
```
Comment (paleolimbot) [inline R/aggregate-rel.R:215]:
```suggestion
      ctx$post_mutate[[name]] <- rlang::as_quosure(expr, env = quo_env)
```

(`ext$quo_env` did not exist, which is why all those warnings were popping up!)

File: R/pkg-arrow.R [hunk 16]
```diff
@@ -44,7 +44,8 @@ ArrowSubstraitCompiler <- R6::R6Class(
       }
 
       plan
-    }
+    },
+    agg_functions = list("sum", "mean", "max", "min", "n_distinct")
```
Comment (paleolimbot) [inline R/pkg-arrow.R:48]:
```suggestion
    .agg_functions = c("sum", "mean", "max", "min", "n_distinct")
```

File: R/pkg-duckdb.R [hunk 17]
```diff
@@ -151,7 +151,8 @@ DuckDBSubstraitCompiler <- R6::R6Class(
         tables = self$named_table_list(),
         as_data_frame = FALSE
       )
-    }
+    },
+    agg_functions = list("sum", "mean", "max", "min", "n", "n_distinct")
```
Comment (paleolimbot) [inline R/pkg-duckdb.R:155]:
```suggestion
    .agg_functions = c("sum", "mean", "max", "min", "n", "n_distinct")
```

File: R/compiler.R [hunk 18]
```diff
@@ -88,6 +88,10 @@ SubstraitCompiler <- R6::R6Class(
       }
     },
 
+    #' @description
+    #' List the aggregate functions implemented by this compiler
+    agg_functions = list(),
```
Comment (paleolimbot) [inline R/compiler.R:93]:
```suggestion
    .agg_functions = c(),
```

File: R/aggregate-rel.R [hunk 19]
```diff
@@ -99,3 +116,105 @@ substrait_group_by <- function(.compiler, ...) {
...
+      value <- as_substrait_expression(quosure, compiler = .compiler)
+
+      # Scalars need to be added to post_mutate because they don't need
+      # to be sent to the query engine as an aggregation
+      ctx$post_mutate[[name]] <- value
+    }
+
+    # Start inspecting the expr to see what aggregations it involves
+    outer_agg <- funs_in_expr[1] %in% .compiler$agg_functions
+    inner_agg <- funs_in_expr[-1] %in% .compiler$agg_functions
```
Comment (paleolimbot) [inline R/aggregate-rel.R:190]:
```suggestion
    outer_agg <- funs_in_expr[1] %in% .compiler$.agg_functions
    inner_agg <- funs_in_expr[-1] %in% .compiler$.agg_functions
```

File: R/aggregate-rel.R [hunk 20]
```diff
@@ -99,3 +116,105 @@ substrait_group_by <- function(.compiler, ...) {
...
+
+    # First, pull out any aggregations wrapped in other function calls
+    if (any(inner_agg)) {
+      expr <- extract_aggregations(expr, ctx, .compiler$agg_functions)
```
Comment (paleolimbot) [inline R/aggregate-rel.R:194]:
```suggestion
      expr <- extract_aggregations(expr, ctx, .compiler$.agg_functions)
```

File: tests/testthat/test-aggregate-rel.R [hunk 21]
```diff
@@ -16,6 +16,7 @@ test_that("substrait_group_by() / substrait_ungroup() (un) set the grouping", {
 test_that("substrait_aggregate() can evaluate a simple aggregation expression", {
   compiler <- substrait_compiler(data.frame(a = c(1, 1, 2, 2, 3), b = 1:5))
   compiler$.fns$sum <- function(x) substrait_call_agg("sum", x)
+  compiler$agg_functions <- list("sum")
```
Comment (paleolimbot) [inline tests/testthat/test-aggregate-rel.R:19]:
```suggestion
  compiler$agg_functions <- c("sum")
```

**Review by paleolimbot — APPROVED** [review]
Just a few last nits!

File: R/aggregate-rel.R (hunk 11 above)
Comment (thisisnic) [reply R/aggregate-rel.R]: Thanks; added a test for this now.

**Review by paleolimbot — APPROVED** [review]
